package main

import (
	"archive/zip"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCodexPlanAndManifest(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, filepath.Join(root, "CLAUDE.md"), "# Instructions\n")
	mustWrite(t, filepath.Join(root, ".claude", "skills", "review", "SKILL.md"), "---\nname: review\n---\nReview.\n")
	mustWrite(t, filepath.Join(root, ".claude", "commands", "fix.md"), "---\ndescription: Fix it\n---\nDo the work.\n")

	r, err := apply(codex(root, detectClaude(root)), root, false, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(r.Written) != 3 {
		t.Fatalf("wrote %d files, want 3: %#v", len(r.Written), r.Written)
	}
	if got := mustRead(t, filepath.Join(root, "AGENTS.md")); got != "# Instructions\n" {
		t.Fatalf("AGENTS.md = %q", got)
	}
	if !exists(filepath.Join(root, ".agents", "skills", "review", "SKILL.md")) {
		t.Fatal("skill was not copied")
	}
	m := loadManifest(root)
	if m.Generated["AGENTS.md"].Direction != "to-codex" {
		t.Fatalf("manifest direction = %q", m.Generated["AGENTS.md"].Direction)
	}
}

func TestFrontmatterAndToolMappings(t *testing.T) {
	m, body := frontmatter("---\nname: reviewer\ntools: [Read, Bash]\n---\nBody\n")
	if body != "Body\n" || m["name"] != "reviewer" {
		t.Fatalf("frontmatter = %#v, body = %q", m, body)
	}
	tools, unknown := claudeTools(m["tools"])
	if len(unknown) != 0 || len(tools) != 2 || tools[0] != "read" || tools[1] != "execute" {
		t.Fatalf("tools = %#v, unknown = %#v", tools, unknown)
	}
}

func TestSyncClaudeWritesAFullMarkedInstructionFile(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, filepath.Join(root, "CLAUDE.md"), "# Source of truth\n\nFollow this.\n")

	if _, err := apply(syncClaude(root, detectClaude(root), "codex"), root, false, false); err != nil {
		t.Fatal(err)
	}
	got := mustRead(t, filepath.Join(root, "AGENTS.md"))
	if !strings.Contains(got, "# Source of truth") || !strings.Contains(got, "generated by agentconv from CLAUDE.md") {
		t.Fatalf("AGENTS.md should be a full, marked copy: %q", got)
	}
}

func TestConfirmationRequiresAnAffirmativeAnswer(t *testing.T) {
	p := newPlan("to-codex")
	p.add(fileOp{Path: "AGENTS.md"})
	p.warn("agent definitions are skipped")
	if !confirm(strings.NewReader("yes\n"), io.Discard, p) {
		t.Fatal("yes should confirm")
	}
	if confirm(strings.NewReader("no\n"), io.Discard, p) {
		t.Fatal("no must cancel")
	}
	if confirm(strings.NewReader(""), io.Discard, p) {
		t.Fatal("empty input must cancel")
	}
}

func TestUpdateURLAndConfirmation(t *testing.T) {
	url, err := updateURL()
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(url, "https://github.com/chrisle/agentconv/releases/latest/download/agentconv-") {
		t.Fatalf("unexpected update URL: %s", url)
	}
	if !confirmUpdate(strings.NewReader("y\n"), io.Discard, "/tmp/agentconv", url) {
		t.Fatal("y should confirm update")
	}
	if confirmUpdate(strings.NewReader("\n"), io.Discard, "/tmp/agentconv", url) {
		t.Fatal("empty response must cancel update")
	}
}

func TestExtractMacOSUpdate(t *testing.T) {
	archivePath := filepath.Join(t.TempDir(), "agentconv.zip")
	file, err := os.Create(archivePath)
	if err != nil {
		t.Fatal(err)
	}
	writer := zip.NewWriter(file)
	entry, err := writer.Create("agentconv-darwin-arm64")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := entry.Write([]byte("binary")); err != nil {
		t.Fatal(err)
	}
	if err := writer.Close(); err != nil {
		t.Fatal(err)
	}
	if err := file.Close(); err != nil {
		t.Fatal(err)
	}

	binary, err := extractMacOSUpdate(archivePath, filepath.Dir(archivePath))
	if err != nil {
		t.Fatal(err)
	}
	defer os.Remove(binary)
	if got := mustRead(t, binary); got != "binary" {
		t.Fatalf("extracted data = %q", got)
	}
}

func mustWrite(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
}

func mustRead(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}
